name: "Terraform GCP Deployment"

on:
  push:
    branches:
      - feature/ci_cd_implementation # Runs when changes are pushed to master branch
#    paths:
#      - "**.tf" # Runs only when Terraform files change

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          credentials_json: ${{ secrets.TERRAFORM_GITHUB_SA_SECRET }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.TERRAFORM_GITHUB_SA_SECRET }}

      # Initialize Terraform
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="credentials=${GOOGLE_APPLICATION_CREDENTIALS}"

      # Plan Terraform (check for changes)
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Approval for Apply
      - name: Wait for manual approval
        uses: hmarr/auto-approve-action@v3

      # Terraform Apply (Deploy Changes) - Requires push confirmation
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan